### ISSUE TITLE
Ball can ignore perfectly timed kicks and pass through catch radius

### ISSUE THREAD

**Issue by zarakon** [supraball/issues#26]
I started taking videos of all of my questionable missed blocks as goal keeper.  Most of them showed that I was just barely out of reach or kicking a little too late.  But a few of them showed the ball passing straight through my kick blocks, and even through my catch radius.

Here is a video showing two of the best examples: http://youtu.be/rLQL5u5Qmww
Make sure to view in 720p to see the middle radar details

**Comment by DavidM1337** [comment]
The question is, what was your ping? You always have a delay online.

**Comment by zarakon** [comment]
I think it's typically around 80, Texas to New York

Most FPS games these days have client-side hit detection.  Is that not the case here?

**Comment by DavidM1337** [comment]
That wouldn't make sense for us, because the ball is running on the server. If it was client side, imagine what would happen, the ball would be warping around because someone with a ping of 1000 hit it on his screen 1 second ago. it would result in a total mess.
so: no, its server side. only the kick effect you see is client side.

**Comment by Timoses** [comment]
There's a big difference in playing online and on lan games (unfortunately). The internet is so imperfect :P.

I just looked at your video. It's not possible to sync everybody at the same time. Imagine this:
You volley the ball and your client decides, that you hit the ball. So you let the server know this. Another guy though (standing right behind you) did not get this yet and thinks the ball is still coming and also volleys it (maybe in order to shoot a goal). But then the server tells that goal shooting client "sorry, the other guy hit first" and places the ball to a completely different spot.
Now one can imagine how complicated this can get, and if you add in that you want a clean ball movement, this seems impossible with client side hit (ball movement) decisions.

I give you a hint to improve goal keeping though: Don't aim frontal are partly frontal (45°) to the ball, but sideways (90°) and then take a volley. This increases your chance to hit the ball immensely since you increase the hit area in which the ball might travel between your hit and the delayed receiving of the server.

**Comment by AlonTavor** [comment]
I fully understand the problems caused by lag compensating and taking back in time physics obeying objects.

However, I do think in a game like this the ball should be lag compensated to a degree, of say, maximum 100ms. Problem is I am pretty sure UE3 does not support "lag compensating non-player entities" like most engines and it will have to be written from scratch. (or maybe it does?) 

Another solution is to lag compensate hit checks on the ball (Again, up to 100-200ms (Or a variable set by the server owner) to not cause weird glitches, Like David's case of a player with 1000ms ping) but not to recalculate where it would be if it was hit at that point, only to apply the speed change from its current position. of course, you'll have to account for cases where server-side the ball is already behind the player to make sure the player doesn't kick the ball into himself.

Please think about that, Players with more than 100ms ping are extremely handicapped as goalies and it could be somewhat easily fixed. Saying "The internet is imperfect" is the lazy man's solution.

**Comment by Timoses** [comment]
I don't fully understand your approach. Lag compensation? Do you mean: Allow a tolerance in which the server does acknowledge the ball direction change by the player who (serversided) hit too late (clientsided he did hit at the right time).
But this would lead to this:
Players seeing the highpinger changing the direction of the ball even though the ball is already out of his reach.

The way it's done right now is that the server is the authoritative instance. The clients have a ball that is simulated in its movement. When another client hits the ball, this hit information needs to travel to the server, be acknowledged by the server and then sent to every client so they see the impact on the ball. 

Well, while elaborating on this and thinking about it: A tolerance might be managable? But still, in a clash for example where multiple players try to volley the ball and one is a high- and the other a lowpinger. Who get's to volley the ball? The highpinger? The lowpinger would take the impression that the game was laggy (even though he has a good ping).

Also while shooting a goal. A guy with a good ping would see the ball go into the net. With an allowed tolerance the highpinger could hit the ball leading to a non goal (even though the ball went in).

You (or me myself) almost convinced me, but however I seem to turn it, everything seems to end in a laggier game for the "good" pingers.

Good news is: We're on a server browser ping fix. : ).

**Comment by Marenz** [comment]
LagCompensation usual means that the players play some time in the past, usually 50-100ms, in extreme cases maybe 200ms. TF2 and Natural Selection 2 do that with the noticable effect that you can die from an attacker even though you felt you ducked in time / ran around the corner before you could be hit. 

That is pretty much the only problem those games have. A delayed hit has no further consequences other than it looking a bit weird to the one being hit. (Okay it gets complicated if the now dead player kills someone else after he is around the corner but the other one already killed him, but let's leave that aside)

If the object being hit is a ball, you can't apply a hit in the past. You can correct the ball like that as timo already mentioned.

I think the concepts are actually clear two all participants here. And what you are describing is basically a very light version of that.. but I don't think it would work nor be fair to the other players.
And I think it would be very very ugly from the technical side. And in UDK it's not doable anyway, that would need to wait for UE4.

I simply think this game needs to be played with a ping <100ms. Then again, I've seen players with ping 150 and more doing not bad. You can get used to it.

**Comment by AlonTavor** [comment]
I don't think it will cause any weird/unfair glitches with the maximum
tolerance set to just 100ms, and it will greatly decrease ping problems of
goalies. However I understand UE3 probably can't be configured to do lag
compensation on a physics object and there's a lot of complicated code and
algorithms involved if you were to write it yourself.

But if by any chance UE3 CAN do that, might want to enable it and just give
it a shot.

**Comment by Timoses** [comment]
Might be an interesting idea to do this for goalies only...
But as Marenz said, probably hardly a way in UE3. Actually, slightly close to absolutely impossible with our means :P.

**Comment by Mindflayr** [comment]
I dont know a ton about this stuff, but I do know that a certain Tribes Ascend player known for creating dll injects such as Magic Chain for TA (UE3 engine) was working on Lag Compensating code for the Disk Launcher proportional to the persons Ping, IE Low Pingers wouldnt notice any effect at all, while High Pingers would be able to fire Disks just like Low Pingers without the normal delay. Not sure how he was doing it, if he finished, or if he ran into a wall trying to work with UE3, but it might be worth reaching out to him, he may be willing to share what he did/did not succeed in doing.

http://www.reddit.com/user/ChoiSeung-hyun

**Comment by Marenz** [comment]
We are currently porting to UE4 anyway so any fix would go to that, we won't invest time on this now.
