### ISSUE TITLE
Speedhacks

### ISSUE THREAD

**Issue by ghost** [supraball/issues#68]
Player joined server I was in, was screaming about the field faster than should be possible with a ping of 998 (or was it 988?). When asked, he said he just used Cheat Engine. I assume he just used the cheat engine function to speed up processes.

**Comment by Timoses** [comment]
We're aware of this problem. Unfortunately the "solution" occasionally led to freeze-ups for clients that did not cheat as well.
We have removed that "solution" since it is possible to kick the player via the kick vote functionality. (Simply press ESC, click on the player's name and click "Vote to kick" on the left side.)

**Comment by Marenz** [comment]
Won't fix this in the UDK version, if possible at all. We don't have deep enough access to the engine to fix this.
