### ISSUE TITLE
Build for mac (osx)

### ISSUE THREAD

**Issue by MisterTea** [supraball/issues#83]
Although the UDK only runs on windows, you can package applications for mac.  Please see this link for documentation:

http://udn.epicgames.com/Three/DistributionAppleMac.html

I would love to see this game running on OSX.  If you have any trouble building a mac binary, let me know, I will be able to help.

**Comment by Marenz** [comment]
We're aware of the various packaging methods. With a little trick you can even package it for Linux. 

You say "Buiding a mac Binary" and this is where the problem comes in. 
We can't build binaries. ANY binary. UDK doesn't give you source code access. 
We're stuck with the only binary Epic delivers, which is the "UDK.exe". That's it. 

I am also not willing to invest much time in this as we are porting it to UE4 right now (for which we DO have source code access).

**Comment by MisterTea** [comment]
Gotcha, please let us know when you can make supraball work on mac, looking forward to trying it out.
